### ISSUE TITLE
AttributeError: 'History' object has no attribute '__unicode__'

### ISSUE THREAD

**Issue by mubeta06** [weatherbit/weatherbit-python#8]
Basic weather query is broken. Test with python 2.7 and 3.7 fails with same error on both.

Traceback (most recent call last):
  File "weather.py", line 31, in <module>
    main()
  File "weather.py", line 24, in main
    print(history)
  File "/Users/matbaker/.local/share/virtualenvs/weatherbit-PwXykkHI/lib/python2.7/site-packages/weatherbit/utils.py", line 14, in __str__
    return self.__unicode__().encode('utf8')
AttributeError: 'History' object has no attribute '__unicode__'

**Comment by na-stewart** [comment]
You cant print the forecast object itself, you must print the get_series method
example: print(forecast.get_series(['temp','precip']))

**Comment by na-stewart** [comment]
Fill in the get_series method with the following params ->
    snow
    - Total Snowfall.
    precip - Total Liquid equivalent precipitation.
    snow6h
    - 6h Total Snowfall.
    precip6h
    - 6h Total Liquid equivalent precipitation.
    datetime
    - Datetime object - Datetime (UTC).
    wind_dir
    - Average Wind direction in degrees (0-360).
    wind_spd
    - Average Wind speed.
    rh
    - Average Relative Humidity (%).
    clouds
    - Average Cloud cover (%).
    slp
    - Average Sea level pressure in millibars.
    temp
    - Average Temperature.
    max_temp
    - Maximum Temperature. (daily only)
    min_temp
    - Minimum Temperature. (daily only)
    weather
    - Dict containing day/night weather icon, description, and code.
